### ISSUE TITLE
Build for Intel macs

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [codemerx/CodemerxDecompile#111]
would this be possible? I don't have a Windows machine to build this from myself and I can't seem to download Visual Studio.

**Comment by The-Minecraft-Scientist** [comment]
quickl update, I just installed the dotnet SDK and ran the same commands as your build workflow and everything works. Building for intel macs should be as simple as changing the runtime ID passed into `dotnet`

**Comment by atdimitrov** [comment]
Yes, you are completely right. It is very simple to have a build for x64 MacOS machines and we will include that in the upcoming version.
