### ISSUE TITLE
Suggestion: Add "Previous" & "Next"

### ISSUE THREAD

**Issue by Maelep** [codemerx/CodemerxDecompile#72]
I would like to suggest to add a "Previous" and "Next" button to allow us to navigate in methods.

**Comment by atdimitrov** [comment]
Hey @Maelep. Thank you for your feedback. Can you elaborate on what exactly you think those buttons should do? Should they move between the methods of a class? Or maybe go back and go forward as in browser navigation?

**Comment by Maelep** [comment]
Yes, it should move back and forward like a browser. So, many times I navigate in dll by CTRL + Click on a method/class/... to "discover" what the method do/class contains/... but the bad side is that I have to restart to zero if I want to go back only one "stage" before.

So allowing us to move back and forward could be really great! I used ILSpy or JustDecompile and one of the two have this functionality.

I completely fell in love of your software. First because it's open source, secondly because it follows Visual Studio Code, third because it's sooo good to navigate in files! Like surfing on a wave! I can find all I need, more easily than other softwares! And last, because performance are insane! Love it! Thank you a lot :)

**Comment by atdimitrov** [comment]
Glad to hear you enjoy it. Thank you for your kind words :)

On the subject - yes, that is very valid suggestion. This functionality is actually already there, but it's hidden (the buttons are not visible). As a temporary workaround you can use the keyboard shortcuts `Alt + Left arrow` and `Alt + Right arrow` to go back and forward respectively. These should also work for mice with built in "Back" and "Forward" buttons.

**Comment by Maelep** [comment]
I'll try that! Thank you for your tips! 😊

**Comment by atdimitrov** [comment]
Hi @Maelep, it's been a while :) I have some good news - we've implemented your suggestion. It is worth mentioning that the feature is not part of the VS Code-based UI you've used before but in a brand new one built on top of AvaloniaUI. Give it a try - [AvaloniaUI-based CodemerxDecompile](https://github.com/codemerx/CodemerxDecompile/releases/latest).
