### ISSUE TITLE
Theme setting keeps getting reset to vs-dark on application start

### ISSUE THREAD

**Issue by jeffska** [codemerx/CodemerxDecompile#74]
I changed the theme to Light (vs) in the app. I can see that information is set on the storage.json file when the app exits. When I start the app again, it comes up in the Light them and then immediately switches to Dark. The storage.json then shows vs-dark as the theme setting.

**Comment by atdimitrov** [comment]
Closing this as the VS Code-based UI is deprecated in favour of our new AvaloniaUI-based UI. This renders this issue irrelevant. Feel free to try the new UI [here](https://github.com/codemerx/CodemerxDecompile/releases/latest).
