### ISSUE TITLE
Program fails to open, seems to be a GUI error

### ISSUE THREAD

**Issue by grayson676** [codemerx/CodemerxDecompile#83]
When running the decompiler from CLI i get the following error

`Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
(node:293522) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:293522) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[293522:1214/202020.709156:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
[1]    293522 trace trap (core dumped)  ./CodemerxDecompile
`

Program does not open when using CLI or GUI
running on Manjaro Linux using zsh shell, bash and sh do not work either, however

**Comment by atdimitrov** [comment]
Closing this as the VS Code-based UI is now deprecated, rendering this issue irrelevant. You can try the new UI [here](https://github.com/codemerx/CodemerxDecompile/releases/latest).
