### ISSUE TITLE
Apple silicon native support

### ISSUE THREAD

**Issue by sonerfromnurland** [codemerx/CodemerxDecompile#84]
Is there any plan to support apple silicon chips natively started from m1 series? If so, when?

**Comment by atdimitrov** [comment]
We've thought about it, yes, but we haven't put much priority on it. Do you experience any major issues with it not being native yet apart from the obvious inconvenience of running it using Rosetta?

**Comment by atdimitrov** [comment]
@sonerfromnurland, good news - native support for Apple Silicon is now available. You can get the latest version [here](https://github.com/codemerx/CodemerxDecompile/releases/latest).
