### ISSUE TITLE
Still active project?

### ISSUE THREAD

**Issue by meyverick** [codemerx/CodemerxDecompile#85]
Hello, is this great project still active? Because haven't see any commit in 2 years :(

**Comment by atdimitrov** [comment]
Hello. It is still alive but not as active as I would like it to be. Rather unfortunately, we haven't had much free time to put into it lately.

**Comment by atdimitrov** [comment]
@meyverick Glad to tell you that there has been quite some development lately. You may want to check the newest [version](https://github.com/codemerx/CodemerxDecompile/releases/latest).
